version: '3.8'

services:
  flask-app:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
    networks:
      - mynetwork

  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
